language : node_js
node_js : 
- v10.6.0
after_success : npm run coverage
env:
  global:
  - NODE_ENV="development"
  - TOKEN_KEY="alainsecretkey"
  - DATABASE_URL=postgres://postgres@127.0.0.1:5432/epic_mail
services:
  - postgresql
before_script:
  - psql -c 'create database testepic;' -U postgres
